### ISSUE TITLE
Broken link in `client_side`

### ISSUE THREAD

**Issue by Thomsch** [TellinaTool/tellina_user_experiment#6]
The link [https://homes.cs.washington.edu/~atran35/research/bash_user_experiment/](https://homes.cs.washington.edu/~atran35/research/bash_user_experiment/) in file `tellina_user_experiment/client_side/README.md` is broken. 

What would be an adequate public replacement?

**Comment by anhnamtran** [comment]
Ah the website got taken down as I graduated. Ideally, the directory would be hosted on a page that won't get taken down due to graduation. 

Here are the steps to create a new host:
1. Clone the repository locally
2. Update the Makefile in the local repo with the inteded `HOST` and `HOST_DIR`,
3. Create `HOST_DIR` on `HOST`, and clone the repository into `HOST_DIR`. 
   a. Note that the directory name for the repository on `HOST` should match `DIST_NAME` in the local repo
4. (Optional) Create a `HOST_DIR/staging` and repeat step 3 there if you would like to have a testing website.
5. Run `make all publish-distribution`

Once a new host has been created, the link in `telina_user_experiment/client_side/README.md` can be updated to wherever the new site is. 

I'll get around to updating this soon if no one else picks it up, although it might be better if someone from UW with access to a hosting site can pick it up, as I no longer have access to mine.

**Comment by Thomsch** [comment]
Hello Andrew,

Thank you for the quick response! I'm a new PhD student with Mike and René that will be working on a new user study. I guess it will be my responsibility to set a new host up :)

The instructions are really helpful. Thank you so much!

**Comment by anhnamtran** [comment]
Do let me know if something breaks horribly, as I might be able to help!

**Comment by Thomsch** [comment]
Will do, Thank you for the help!

**Comment by mernst** [comment]
Please make sure that the instructions Andrew gave are in the repository somewhere.  Thanks.
